function love.conf(t)
    t.title = "LuaPong"        -- The title of the window the game is in (string)
    t.author = "Jacob Shaffer"        -- The author of the game (string)
    t.version = "0.9.0"         -- The LÖVE version this game was made for (string)
    t.screen.width = 800        -- The window width (number)
    t.screen.height = 600       -- The window height (number)
    t.screen.fullscreen = false -- Enable fullscreen (boolean)
    t.modules.joystick = false   -- Enable the joystick module (boolean)
    t.modules.mouse = false      -- Enable the mouse module (boolean)
    t.modules.physics = false    -- Enable the physics module (boolean)
end